### ISSUE TITLE
Feature Request: Interface for admins to configure VAN 

### ISSUE THREAD

**Issue by WMudgeEllis** [StateVoicesNational/Spoke#2106]
**Problem**
The only way to update VAN is to use environment variables

**Solution**
Create a ui to change VAN configuration

**Context**
Could use a service manager to handle this functionality. An example can be found  in src/extensions/service-managers/test-fake-example

Creating a service manager could allow the admin to edit the interface, as well as allow us to communicate with the database. May also allow us to address security concerns.

**Discussion/design**

Do these VAN configurations need to be tamperproof? What levels of security do we want to add? How secret are the VAN configurations?

**Comment by WMudgeEllis** [comment]
VAN variables that need be stored somehow: NGP_VAN_API_KEY, NGP_VAN_APP_NAME, NGP_VAN_WEBHOOK_BASE_URL

Service managers create a component (in admin settings) as well as talks to the database. There are good docs in docs/HOWTO-use_service_managers.md

One possible solution is to add them to the JSON blob that is stored in the database under organization.features. The graphql mutation that triggers an addition to the blob is called editOrganization.

The blob may not be the best solution as VAN variables may be secrets, so storing them in a blob in the database is a bad idea.

**Comment by n0land0** [comment]
After spending some time tracing the flow of data around Settings and our VAN service manager, here are our tentative conclusions and questions:

_Things we think we know_
- Data cycle between `form -> onSubmit->updateServiceManager->onOrganizationUpdateSignal` is working
- No VAN data is being written
- Calling some functions in `src/extensions/service-managers/van-api-keys-manager/index.js` breaks rendering (eg adding code to the function body above `getOrganizationData`)

_Things we would like to know in order to proceed_
- How is the `editOrganization` mutation called?
- Why is the default `onUpdateSignal` NOT writing anything?
- What is the larger issue causing the render to break when we add code to functions in `src/extensions/service-managers/van-api-keys-manager/index.js`?

**Comment by n0land0** [comment]
`src/extensions/service-managers/van-api-keys-manager/index.js`

### Weird bug:

- Initially, we were able to write data upon form submission from our service manager to organization.features using a knex query: 
```
export async function onOrganizationUpdateSignal({
  organization,
  user,
  updateData
}) {

>>> start new code
  let orgChanges = {
      features: JSON.stringify({
        write: "test"
      });
    };

  await r
      .knex("organization")
      .where("id", organization.id)
      .update(orgChanges);
>>> end new code

  return {
    data: updateData,
    fullyConfigured: true
  };
}
```

- At some point, the same code we used to successfully write data started breaking the render for our service manager. 
- Initially this was probably caused by trying to stringifying a string, but the problem persists even after destroying the old database and creating a fresh one. 
- VAN service manager can be reliably rendered by removing any code other than the return statement, but even just declaring an object in the function body breaks the render.

**Comment by crayolakat** [comment]
@n0land0 Are you still working on this issue? If so, do you have a branch that I can look at to try and replicate the bug described above?

**Comment by mau11** [comment]
hi @WMudgeEllis  we're reviewing outstanding issues and believe that the API key manager has been fully implemented. If you're still having issues, please feel free to re-open this issue.
