### ISSUE TITLE
Bug: No UI indicating responses when bulk send is enabled

### ISSUE THREAD

**Issue by crayolakat** [StateVoicesNational/Spoke#2210]
**Describe the bug**
When bulk send is enabled, the UI on the Texter TODO list doesn't indicate that there are responses.

**To Reproduce**
1. In your dev environment, enable bulk send with a batch of 30
2. Create a new campaign with 2 test phone numbers
3. Assign yourself as the texter for both phone numbers
4. Start the campaign
5. Switch to texter view
6. Click "SEND MESSAGES"
7. Click "SEND BULK (30)" at the top of the screen
8. Verify that you received the text on both test phone numbers
9. Respond to the text with both numbers
10. In Spoke, go back to the main Texter TODO list
11. **Issue:** There is no UI indicating that you have received 2 responses. There is 1 button that says "SEND MESSAGES". You only see the responses when you click "SEND MESSAGES"

**Expected behavior**
There should be a UI indicating that the count of pending messages that needs responses, like how there is when bulk send isn't enabled.

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9382984/184654815-aace6559-8c58-4c0d-81c7-c32ab0765853.png">

**Platform (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Desktop
 - Version: 104.0.5112.79

**Comment by crayolakat** [comment]
This issue happens even if `Allow 'Send All' single-button` is disabled in the organization settings. This issue will always happen when the `ALLOW_SEND_ALL` environment variable is set to `true`

**Comment by crayolakat** [comment]
Actually, it looks like not having the Respond button for bulk send was intentional: https://github.com/MoveOnOrg/Spoke/blob/36e55956c170add240523c9d75c490cd85adbde6/src/components/AssignmentSummary.jsx#L190-L202

Does anyone know why, and can we revisit this?

**Comment by crayolakat** [comment]
Hey @michael-gratton ! It's my understanding that your organization uses the Bulk Send feature. Do you know if there's a reason why the "Respond" button is disabled when Bulk Send is enabled, and if there will be any negative impact if we enable it?

**Comment by michael-gratton** [comment]
@crayolakat No idea why it was disabled tbh, maybe the feature was developed or evolved into being more of a one-way blast rather than a p2p thing? Working on a few issues with bulk sending earlier in the year it looked like some past changes had been made without taking the bulk send feature into account (understandable given it's mostly being maintained in the US) and which broke when bulk send was enabled, so maybe something similar happened with this?

We'd find it useful - we do enable bulk sends but also want to be able to reply to messages coming in, so no objection re-enabling it here. IIRC we did get some indication if there were waiting messages, but it might not have been an explicit "Respond" - just some other buttons showing up.

Might need some deeper testing to make sure it actually works as expected further down the codepaths when bulk send is enabled as well, would be happy to help review & test.

**Comment by crayolakat** [comment]
Thanks for the context and offer to help review/test @michael-gratton ! Laws in the US regarding bulk send changed recently, so our organization (MoveOn) is now legally able to enable it. We are doing some testing and additional development on the feature. I am wondering what batch size you use when you do bulk send?

**Comment by michael-gratton** [comment]
Hey, sorry about the late response. We have `BULK_SEND_CHUNK_SIZE` set to 400 at the moment. We've tried higher values (up to 1000 from memory), but larger values seems to impact UI responsiveness.

**Comment by crayolakat** [comment]
Issue resolved via merge of https://github.com/MoveOnOrg/Spoke/pull/2303
