### ISSUE TITLE
Mobile-Only Update

### ISSUE THREAD

**Issue by Arique1104** [StateVoicesNational/Spoke#2269]
Make the Texter UI available on Mobile

**Comment by Courtney-Lippman** [comment]
I have created rough draft wireframes for the Texter UI on Mobile. My goal with the mobile views was to mimic the desktop version as closely as possible without crowding the screen. I picked the iPhone SE screen size because it is the middle of the road regarding mobile screen sizes. 
<details>
<summary>Texter UI desktop version for reference:</summary>
<br>
<img width="1435" alt="Screen Shot 2023-04-12 at 5 52 54 PM" src="https://user-images.githubusercontent.com/104169837/231610708-0f5e1467-2988-43c1-be33-779b8b0792a9.png">
</details>

<details>
<summary>Texter UI mobile views I created:</summary>
<br>
<img width="343" alt="Screen Shot 2023-04-12 at 9 25 23 PM" src="https://user-images.githubusercontent.com/104169837/231834112-ebf44490-1cea-4294-8cfe-19410a6d3539.png">
<img width="339" alt="Screen Shot 2023-04-12 at 9 25 44 PM" src="https://user-images.githubusercontent.com/104169837/231834179-1a418339-adb1-46fd-8cf8-4804a9d7bd8f.png">
<img width="335" alt="Screen Shot 2023-04-12 at 9 26 00 PM" src="https://user-images.githubusercontent.com/104169837/231834200-9ee2fd3a-79e5-4224-962a-09296c33e00d.png">
<img width="334" alt="Screen Shot 2023-04-12 at 9 26 11 PM" src="https://user-images.githubusercontent.com/104169837/231834227-46140c74-8537-4da4-9aec-967ace3196e4.png">

</details>

**Comment by Courtney-Lippman** [comment]
I am excited to add wireframes for the modal views for the ALL RESPONSES and OPT-OUT buttons next.
